Repository startersclan/asp, pull requests merged in 2025-02, with the labels that each got.

#80 fix: Grant unlock point per badge instead of per badge level
  src/ASP/aspx/getunlocksinfo.php
Labels: fix

#90 Fix (ci): Drop support for linux/390x
  .github/workflows/ci-master-pr.yml
Labels: fix

#92 Refactor (ci): Update actions to node 20
  .github/workflows/ci-master-pr.yml
Labels: refactor

#81 feat: Allow snapshots to be sent to sendsnapshot.aspx
  config/ASP/etc/nginx/nginx.conf
  src/ASP/.htaccess
Labels: feature
